### ISSUE TITLE
How to use ManualTime to force a ticker to fire?

### ISSUE THREAD

**Issue by justin-infinitusai** [thejerf/abtime#6]
Hi, in a test case I want to use ManualTime to force a ticker running in a separate goroutine to fire. The toy implementation is as follows:

```
package main

import (
	"fmt"
	"time"

	"github.com/thejerf/abtime"
)

func main() {
         t := abtime.NewManual()
	go func() {
		printTicker := t.NewTicker(5*time.Second, 0)
		for {
			select {
			case <-printTicker.Channel():
				fmt.Println("Hello, world!")
			}
		}
	}()
	t.Advance(10 * time.Second)
	time.Sleep(30 * time.Second)
}
```

I expect this code to fire `Hello, world!` twice, but that's not the behavior when I run it. Am I doing this correctly? Is there a better way to do this?

**Comment by thejerf** [comment]
I don't have advancing the time automatically fire tickers because time advancing in real code is not guaranteed to fire tickers. Tickers are fired manually by .Trigger()ing them with their ID.

I realize this may seem like an odd design decision at first, but it is based on the fact that in general goroutine time just doesn't work the way people think it does. This library gives the ability to test even situations that may arise under extreme load, such as a ticker potentially being delayed long past when it should have fired, or two tickers that "should" have one fire before the other fire the wrong one first, and other things that are hard to set up in test code but happen with distressing frequency in production.
